   /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class ClassificationMenu extends javax.swing.JFrame {

    /**
     * Creates new form Result1
     */
    public ClassificationMenu() {
        initComponents();
        this.setLayout(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        lblMovie1 = new javax.swing.JLabel();
        lblMovie2 = new javax.swing.JLabel();
        lblMovie3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        lblGenre1 = new javax.swing.JLabel();
        lblRating1 = new javax.swing.JLabel();
        lblYear1 = new javax.swing.JLabel();
        lblGenre2 = new javax.swing.JLabel();
        lblRating2 = new javax.swing.JLabel();
        lblRating3 = new javax.swing.JLabel();
        lblYear2 = new javax.swing.JLabel();
        lblYear3 = new javax.swing.JLabel();
        lblGenre3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selected Movies");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 769));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton1.setText("Select");

        lblMovie1.setText("Movie Name");

        lblMovie2.setText("Movie Name");

        lblMovie3.setText("Movie Name");

        jRadioButton2.setText("Select");

        jRadioButton3.setText("Select");

        lblGenre1.setText("Genre");

        lblRating1.setText("Rating");

        lblYear1.setText("Year");

        lblGenre2.setText("Genre");

        lblRating2.setText("Rating");

        lblRating3.setText("Rating");

        lblYear2.setText("Year");

        lblYear3.setText("Year");

        lblGenre3.setText("Genre");

        jLabel17.setText("Movie Pic");

        jLabel18.setText("Movie Pic");

        jLabel19.setText("Movie Pic");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovie1)
                            .addComponent(jRadioButton1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRating1)
                                    .addComponent(lblGenre1)
                                    .addComponent(lblYear1)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie2)
                    .addComponent(jRadioButton2)
                    .addComponent(lblGenre2)
                    .addComponent(lblRating2)
                    .addComponent(lblYear2)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie3)
                    .addComponent(jRadioButton3)
                    .addComponent(lblRating3)
                    .addComponent(lblYear3)
                    .addComponent(lblGenre3)
                    .addComponent(jLabel19))
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie1)
                    .addComponent(lblMovie2)
                    .addComponent(lblMovie3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenre1)
                    .addComponent(lblGenre2)
                    .addComponent(lblGenre3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRating1)
                    .addComponent(lblRating2)
                    .addComponent(lblRating3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear1)
                    .addComponent(lblYear2)
                    .addComponent(lblYear3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(27, 27, 27))
        );

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoose)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnChoose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        //Deklarasi string choose
        String choose = " ";
        //Kondisi kalau radio button 1,atau 2, atau 3 di pilih
        if (jRadioButton1.isSelected()){
            int n;
            n = JOptionPane.showConfirmDialog(
                    btnChoose,
                    "Are You sure choosing this movie recommendation?",
                    "A certain Question",
                    JOptionPane.YES_NO_OPTION);
            Result1 x = new Result1();
            Result1.txtMovie.setText(ClassificationMenu.lblMovie1.getText());
            Result1.txtGenre.setText(ClassificationMenu.lblGenre1.getText());
            Result1.txtRating.setText(ClassificationMenu.lblRating1.getText());
            x.setVisible(true);
        }
       if (jRadioButton2.isSelected()){
            int n;
            n = JOptionPane.showConfirmDialog(
                    btnChoose,
                    "Are You sure choosing this movie recommendation?",
                    "A certain Question",
                    JOptionPane.YES_NO_OPTION);
            Result1 x = new Result1();
            Result1.txtMovie.setText(ClassificationMenu.lblMovie2.getText());
            Result1.txtGenre.setText(ClassificationMenu.lblGenre2.getText());
            Result1.txtRating.setText(ClassificationMenu.lblRating2.getText());
            x.setVisible(true);
        }
       if (jRadioButton3.isSelected()){
            int n;
            n = JOptionPane.showConfirmDialog(
                    btnChoose,
                    "Are You sure choosing this movie recommendation?",
                    "A certain Question",
                    JOptionPane.YES_NO_OPTION);
            Result1 x = new Result1();
            Result1.txtMovie.setText(ClassificationMenu.lblMovie3.getText());
            Result1.txtGenre.setText(ClassificationMenu.lblGenre3.getText());
            Result1.txtRating.setText(ClassificationMenu.lblRating3.getText());
            x.setVisible(true);
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassificationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassificationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassificationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassificationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //List of movies name
        ArrayList<String> rating = new ArrayList<String>();
          rating.add("*");
          rating.add("**");
          rating.add("***");
          rating.add("****");
          rating.add("*****");
        ArrayList<String> movies = new ArrayList<String>();
        movies.add("Jurassic Park 2");
        movies.add("Big Hero 6");
        movies.add("My Gangnam Beauty");
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassificationMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JLabel lblGenre1;
    public static javax.swing.JLabel lblGenre2;
    public static javax.swing.JLabel lblGenre3;
    public static javax.swing.JLabel lblMovie1;
    public static javax.swing.JLabel lblMovie2;
    public static javax.swing.JLabel lblMovie3;
    public static javax.swing.JLabel lblRating1;
    public static javax.swing.JLabel lblRating2;
    public static javax.swing.JLabel lblRating3;
    public static javax.swing.JLabel lblYear1;
    public static javax.swing.JLabel lblYear2;
    public static javax.swing.JLabel lblYear3;
    // End of variables declaration//GEN-END:variables
}
