/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author FX8800
 */
public class MainMenu extends javax.swing.JFrame {
    

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
       Image icon = Toolkit.getDefaultToolkit().getImage("src/finalproject/Logo2.png");
        setIconImage(icon);
        setTitle("DP MSE");
    }
    AddMovie menu = new AddMovie();
     

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGenre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbRat = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 206, 201));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel2.setBackground(new java.awt.Color(0, 206, 201));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("WELCOME TO DP MOVIE SEARCH ENGINE ");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Logo3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(0, 206, 201));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        jLabel1.setText("Genre");

        cbGenre.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        cbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        jLabel4.setText("Rating");

        cbRat.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        cbRat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRatActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 11)); // NOI18N
        jButton2.setText("Advanced Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setText("Advanced Search!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbRat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 206, 201));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        txtSearch.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/iconmonstr-magnifier-4-16.png"))); // NOI18N
        jButton1.setText("Search Movie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cbGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenreActionPerformed
        // TODO add your handling code here:
       String[] genreString = { "Horror", "Drama", "Romance", "Fantasy", "Action" };
       cbGenre genreList = new cbGenre(genreString);
       genreList.setSelectedIndex(4);
       genreList.addActionListener(this);
       this.setVisible(true);
        
    }//GEN-LAST:event_cbGenreActionPerformed

    private void cbRatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRatActionPerformed
        // TODO add your handling code here:
       String[] ratString = { "*", "**", "***", "****", "*****" };
       cbRat ratList = new cbRat(ratString);
       ratList.setSelectedIndex(4);
       ratList.addActionListener(this);
       this.setVisible(true);
    }//GEN-LAST:event_cbRatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> e = menu.horrorList().get(0);
        ArrayList<String> e1 = menu.horrorList().get(1);
        ArrayList<String> e2 = menu.horrorList().get(2);
        ArrayList<String> e3 = menu.horrorList().get(3);
        ArrayList<String> e4 = menu.horrorList().get(4);
        String f = e.get(0);
        String g = e.get(1);
        String h = e.get(2);
        String f1 = e1.get(0);
        String g1 = e1.get(1);
        String h1 = e1.get(2);
        String f2 = e2.get(0);
        String g2 = e2.get(1);
        String h2 = e2.get(2);
        String f3 = e3.get(0);
        String g3 = e3.get(1);
        String h3 = e3.get(2);
        String f4 = e4.get(0);
        String g4 = e4.get(1);
        String h4 = e4.get(2);
       
        ArrayList<String> ea = menu.fantasyList().get(0);
        ArrayList<String> ea1 = menu.fantasyList().get(1);
        ArrayList<String> ea2 = menu.fantasyList().get(2);
        ArrayList<String> ea3= menu.fantasyList().get(3);
        ArrayList<String> ea4 = menu.fantasyList().get(4);
        String fa = ea.get(0);
        String ga = ea.get(1);
        String ha = ea.get(2);
        String fa1 = ea1.get(0);
        String ga1 = ea1.get(1);
        String ha1 = ea1.get(2);
        String fa2 = ea2.get(0);
        String ga2 = ea2.get(1);
        String ha2 = ea2.get(2);
        String fa3 = ea3.get(0);
        String ga3 = ea3.get(1);
        String ha3 = ea3.get(2);
        String fa4 = ea4.get(0);
        String ga4 = ea4.get(1);
        String ha4 = ea4.get(2);
        
        ArrayList<String> eb = menu.dramaList().get(0);
        ArrayList<String> eb1 = menu.dramaList().get(1);
        ArrayList<String> eb2 = menu.dramaList().get(2);
        ArrayList<String> eb3= menu.dramaList().get(3);
        ArrayList<String> eb4 = menu.dramaList().get(4);
        String fb = eb.get(0);
        String gb = eb.get(1);
        String hb = eb.get(2);
        String fb1 = eb1.get(0);
        String gb1 = eb1.get(1);
        String hb1 = eb1.get(2);
        String fb2 = eb2.get(0);
        String gb2 = eb2.get(1);
        String hb2 = eb2.get(2);
        String fb3 = eb3.get(0);
        String gb3 = eb3.get(1);
        String hb3 = eb3.get(2);
        String fb4 = eb4.get(0);
        String gb4 = eb4.get(1);
        String hb4 = eb4.get(2);
        
        ArrayList<String> ec = menu.romanceList().get(0);
        ArrayList<String> ec1 = menu.romanceList().get(1);
        ArrayList<String> ec2 = menu.romanceList().get(2);
        ArrayList<String> ec3= menu.romanceList().get(3);
        ArrayList<String> ec4 = menu.romanceList().get(4);
        String fc = ec.get(0);
        String gc = ec.get(1);
        String hc = ec.get(2);
        String fc1 = ec1.get(0);
        String gc1 = ec1.get(1);
        String hc1 = ec1.get(2);
        String fc2 = ec2.get(0);
        String gc2 = ec2.get(1);
        String hc2 = ec2.get(2);
        String fc3 = ec3.get(0);
        String gc3 = ec3.get(1);
        String hc3 = ec3.get(2);
        String fc4 = ec4.get(0);
        String gc4 = ec4.get(1);
        String hc4 = ec4.get(2);
        
        ArrayList<String> ed = menu.actionList().get(0);
        ArrayList<String> ed1 = menu.actionList().get(1);
        ArrayList<String> ed2 = menu.actionList().get(2);
        ArrayList<String> ed3= menu.actionList().get(3);
        ArrayList<String> ed4 = menu.actionList().get(4);
        String fd = ed.get(0);
        String gd = ed.get(1);
        String hd = ed.get(2);
        String fd1 = ed1.get(0);
        String gd1 = ed1.get(1);
        String hd1 = ed1.get(2);
        String fd2 = ed2.get(0);
        String gd2 = ed2.get(1);
        String hd2 = ed2.get(2);
        String fd3 = ed3.get(0);
        String gd3 = ed3.get(1);
        String hd3 = ed3.get(2);
        String fd4 = ed4.get(0);
        String gd4 = ed4.get(1);
        String hd4 = ed4.get(2);
        
 
       

        String a = cbGenre.getSelectedItem().toString();
        String b = cbRat.getSelectedItem().toString();
        int c = cbGenre.getSelectedIndex();
        int d = cbRat.getSelectedIndex();
 

        if(c == 0 && d == 0 ){
            ClassificationMenu.lblMovie1.setText(f);
            ClassificationMenu.lblMovie2.setText(g);
            ClassificationMenu.lblMovie3.setText(h);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 0 && d == 1){
            ClassificationMenu.lblMovie1.setText(f1);
            ClassificationMenu.lblMovie2.setText(g1);
            ClassificationMenu.lblMovie3.setText(h1);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 0 && d == 2){
            ClassificationMenu.lblMovie1.setText(f2);
            ClassificationMenu.lblMovie2.setText(g2);
            ClassificationMenu.lblMovie3.setText(h2);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 0 && d == 3){
            ClassificationMenu.lblMovie1.setText(f3);
            ClassificationMenu.lblMovie2.setText(g3);
            ClassificationMenu.lblMovie3.setText(h3);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 0 && d == 4){
            ClassificationMenu.lblMovie1.setText(f4);
            ClassificationMenu.lblMovie2.setText(g4);
            ClassificationMenu.lblMovie3.setText(h4);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 1 && d == 0){
            ClassificationMenu.lblMovie1.setText(fd);
            ClassificationMenu.lblMovie2.setText(gd);
            ClassificationMenu.lblMovie3.setText(hd);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 1 && d == 1){
           ClassificationMenu.lblMovie1.setText(fd1);
            ClassificationMenu.lblMovie2.setText(gd1);
            ClassificationMenu.lblMovie3.setText(hd1);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 1 && d == 2){
            ClassificationMenu.lblMovie1.setText(fd2);
            ClassificationMenu.lblMovie2.setText(gd2);
            ClassificationMenu.lblMovie3.setText(hd2);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 1 && d == 3){
            ClassificationMenu.lblMovie1.setText(fd3);
            ClassificationMenu.lblMovie2.setText(gd3);
            ClassificationMenu.lblMovie3.setText(hd3);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 1 && d == 4){
           ClassificationMenu.lblMovie1.setText(fd4);
            ClassificationMenu.lblMovie2.setText(gd4);
            ClassificationMenu.lblMovie3.setText(hd4);
        } else if (c == 2 && d == 0){
           ClassificationMenu.lblMovie1.setText(fa);
            ClassificationMenu.lblMovie2.setText(ga);
            ClassificationMenu.lblMovie3.setText(ha);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 2 && d == 1){
            ClassificationMenu.lblMovie1.setText(fa1);
            ClassificationMenu.lblMovie2.setText(ga1);
            ClassificationMenu.lblMovie3.setText(ha1);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 2 && d == 2){
           ClassificationMenu.lblMovie1.setText(fa2);
            ClassificationMenu.lblMovie2.setText(ga2);
            ClassificationMenu.lblMovie3.setText(ha2);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 2 && d == 3){
            ClassificationMenu.lblMovie1.setText(fa3);
            ClassificationMenu.lblMovie2.setText(ga3);
            ClassificationMenu.lblMovie3.setText(ha3);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 2 && d == 4){
           ClassificationMenu.lblMovie1.setText(fa4);
            ClassificationMenu.lblMovie2.setText(ga4);
            ClassificationMenu.lblMovie3.setText(ha4);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 3 && d == 0){
            ClassificationMenu.lblMovie1.setText(fc);
            ClassificationMenu.lblMovie2.setText(gc);
            ClassificationMenu.lblMovie3.setText(hc);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 3 && d == 1){
           ClassificationMenu.lblMovie1.setText(fc1);
            ClassificationMenu.lblMovie2.setText(gc1);
            ClassificationMenu.lblMovie3.setText(hc1);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 3 && d == 2){
           ClassificationMenu.lblMovie1.setText(fc2);
            ClassificationMenu.lblMovie2.setText(gc2);
            ClassificationMenu.lblMovie3.setText(hc2);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 3 && d == 3){
          ClassificationMenu.lblMovie1.setText(fc3);
            ClassificationMenu.lblMovie2.setText(gc3);
            ClassificationMenu.lblMovie3.setText(hc3);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 3 && d == 4){
           ClassificationMenu.lblMovie1.setText(fc4);
            ClassificationMenu.lblMovie2.setText(gc4);
            ClassificationMenu.lblMovie3.setText(hc4);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 4 && d == 0){
           ClassificationMenu.lblMovie1.setText(fb);
            ClassificationMenu.lblMovie2.setText(gb);
            ClassificationMenu.lblMovie3.setText(hb);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 4 && d == 1){
            ClassificationMenu.lblMovie1.setText(fb1);
            ClassificationMenu.lblMovie2.setText(gb1);
            ClassificationMenu.lblMovie3.setText(hb1);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 4 && d == 2){
            ClassificationMenu.lblMovie1.setText(fb2);
            ClassificationMenu.lblMovie2.setText(gb2);
            ClassificationMenu.lblMovie3.setText(hb2);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 4 && d == 3){
            ClassificationMenu.lblMovie1.setText(fb3);
            ClassificationMenu.lblMovie2.setText(gb3);
            ClassificationMenu.lblMovie3.setText(hb3);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        } else if (c == 4 && d == 4){
            ClassificationMenu.lblMovie1.setText(fb4);
            ClassificationMenu.lblMovie2.setText(gb4);
            ClassificationMenu.lblMovie3.setText(hb4);
            ClassificationMenu.lblGenre1.setText(a);
            ClassificationMenu.lblGenre2.setText(a);
            ClassificationMenu.lblGenre3.setText(a);
            ClassificationMenu.lblRating1.setText(b);
            ClassificationMenu.lblRating2.setText(b);
            ClassificationMenu.lblRating3.setText(b);
        }

        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        ArrayList<String> e = menu.horrorList().get(0);
        if ( search.equals(e)){
            Result1.txtMovie.setText(e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
       try{
       } catch (Exception e){
           System.out.println(e);
           UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
       }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbGenre;
    public static javax.swing.JComboBox<String> cbRat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void add(cbGenre cb) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
